
name: time_master_app
description: A customizable digital time app.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.1
  google_fonts: ^6.1.0
  flutter_colorpicker: ^1.0.3
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  uuid: ^4.2.1 

  flutter_launcher_icons: ^0.13.1 # or latest

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/clock.png" # your icon path
  min_sdk_android: 21 # optional

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/meeram.jpg
    - assets/images/mirqal.jpg
